### ISSUE TITLE
how to fix "Missing import: UnionFS" ?

### ISSUE THREAD

**Issue by sergey6661313** [gobolinux/Compile#55] opened 2022-04-17 14:46 UTC
I just fresh install gobolinux and completed all instuctions in GoboLinux-017-Known-Issues-and-Fixes. 
but i see Missing import: UnionFS if use Compile util...

**Comment by Nuc1eoN** [comment] 2022-08-24 13:19
Hi @sergey6661313, where do you see this?

**Comment by sergey6661313** [comment] 2022-08-27 10:32
I ran gobos in virtualbox. And then deleted that image. Now I can't repeat that mistake.
But I remember that this problem created only if i install gobolinux AFTER all "Issues-and-Fixes" on USB-live system. 

I have to it non exactly like wiki. 
example: 
i run commands 
    "InstallPackage https://gobolinux.org/packages/017/Fuse--2.9.7--x86_64.tar.bz2"
    "InstallPackage https://gobolinux.org/packages/017/UnionFS-Fuse--2.1--x86_64.tar.bz2" 
with flag "--no-check-certificate" because certificate non work on live system.

i run 
    "Compile --no-check-certificate Automake 1.16.4" 
and 
    "Compile --no-check-certificate  DebianUtils 5.7"
before 
    "sudo Compile --no-check-certificate CA-Certificates" 
because  flag "--no-check-certificate" non inherent for dependencies in compile tool.

If i install Gobo without all of this - Compile working...

**Comment by Nuc1eoN** [comment] 2024-04-17 01:40
Closing for now because cannot be reproduced

If it happens again feel free to shoot a message with reproducible steps :pray:

**Closed by Nuc1eoN** 2024-04-17 01:40 UTC
